export enum Error {
    BracketError = 'incorrect brackets order',
    UnexpectedClosingBracketError = 'unexpected closing bracket',
    UnclosedBracketError = 'unclosed opening bracket',
    BracketAdjacentCharactersError = 'adjacent characters are not correct', 
    ZeroDivisionError = 'division by Zero',
    UnexpectedActionError = 'Unexpected action or function',
    LineStartError = 'incorrect start of expression',
    LineEndtError = 'incorrect end of expression',
    IncorectActionQueueError = 'incorect actions queueu',
    UnknownSymbolError = 'uknown sybols',
    IncorrectFunctinNameError = 'incorrect function name',
    NumberPointError = 'number with several points',
    PointError = 'point in incorrect place',
}